### ISSUE TITLE
How to change promcord port?

### ISSUE THREAD

**Issue by FlorianD78** [Biospheere/promcord#218]
## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the latest promcord version

## Question

Hello, I want to change the port of promcord exporter. I change it in docker-compose.yaml, prometheus.yml and grafana.json but it still not working. I would like to know if there is something else to change?  

## Steps to reproduce

docker-compose.yml:
```yaml
  promcord:
    image: "biospheere/promcord"
    restart: always
    env_file: .env
    container_name: "promcord"
    expose:
      - 7000
```

prometheus.yml:
```yaml

scrape_configs:
  - job_name: 'discord'
    static_configs:
      - targets: ['promcord:7000']
```

grafana.json (l.83-84):
```json
"fields": "/^discord_ping_websocket{instance=\"promcord:7000\", job=\"discord\"}$/",
"values": false
```
